import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import DashboardNavbar from "@/components/dashboard-navbar";
import DashboardSiderbar from "@/components/dashboard-siderbar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <DashboardNavbar />

        <div className="flex">
          <div className="hidden border-r pt-4 bg-gray-50 md:block w-[280px] h-auto">
            <DashboardSiderbar />
          </div>
          <div className="flex h-auto w-full md:max-w-[1120px]">
            <SessionProvider>{children}</SessionProvider>
            <Toaster position="top-center" />
          </div>
        </div>
      </body>
    </html>
  );
}
